# Generated by Django 3.2.7 on 2021-09-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_desc', models.CharField(max_length=1000)),
                ('product_quantity', models.IntegerField(default=0)),
                ('product_price', models.IntegerField()),
            ],
        ),
    ]
